### ISSUE TITLE
请问您是通过什么方式在coco2017test-dev数据集上得到的测试结果？为什么我在coco2017testdev上eval生成的json文件特别大，并且上传coco官网评估会出错？

### ISSUE THREAD

**Issue by fengchuibeixiang** [junjiehe96/FastInst#13]
你好，这是一项非常棒的工作！
我正在复现你们的论文成果，但是
python train_net.py --eval-only --num-gpus 2 --config-file configs/coco/instance-segmentation/fastinst_R50_ppm-fpn_x1_576.yaml MODEL.WEIGHTS /path/to/checkpoint_file
我运行了上面的代码，权重文件是在这里下载的，测试数据集改成了coco2017test-dev，并下载了相应的标注json文件，评估结束之后在output路径下生成了对应的json文件，但是这个json文件特别大，1.1G左右，如果不使用test-dev而是test的话则有2.6G。然后我按coco官网评估要求修改了文件名称，上传json文件到服务器，都没有成功
第一次上传报错：
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpa2BTU6/run/program/run.py", line 112, in 
    res.extend(json.load(data_file))
  File "/opt/conda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/conda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 48971776 (char 48971775)
第二次上传报错：
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpC6m7hj/run/program/run.py", line 120, in 
    cocoDt=cocoGt.loadRes(resFile)
  File "/opt/conda/lib/python2.7/site-packages/pycocotools/coco.py", line 309, in loadRes
    anns = json.load(open(resFile))
  File "/opt/conda/lib/python2.7/json/__init__.py", line 287, in load
    return loads(fp.read(),
MemoryError
第三次上传报错：
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
还请指教，谢谢！

**Comment by fengchuibeixiang** [comment]
今天又试了一次，终于成功了
