### ISSUE TITLE
Inference demo.py

### ISSUE THREAD

**Issue by GreaBugs** [junjiehe96/FastInst#7]
0%|          | 0/76 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data3/shenbaoyue/code/FastInst-try-maskattention/demo/demo.py", line 123, in <module>
    img = read_image(path, format="BGR")
  File "/data3/shenbaoyue/code/FastInst-try-maskattention/detectron2/detectron2/data/detection_utils.py", line 180, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/data3/shenbaoyue/anaconda3/envs/fastry/lib/python3.8/site-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/data3/shenbaoyue/anaconda3/envs/fastry/lib/python3.8/site-packages/iopath/common/file_io.py", line 604, in _open
    return open(  # type: ignore
IsADirectoryError: [Errno 21] Is a directory: '/'

进程已结束,退出代码1

How can I resolve this error when I configure the parameters to run demo demo. py? The training process is normal. I have tried to solve it online but it has not been successful. I would greatly appreciate it if I could receive assistance

**Comment by GreaBugs** [comment]
I have resolved the issue and the input needs to be a list.
